import os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import docx
from docx.shared import Pt, RGBColor


def _bullet_list(items):
    return items or ["None identified"]


def generate_pdf_report(analysis: dict, document_filename: str, output_path: str) -> str:
    doc = SimpleDocTemplate(output_path, pagesize=letter,
                             topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], textColor=colors.HexColor("#1f3a5f"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#1f3a5f"),
                         spaceBefore=14, spaceAfter=6)
    body = styles["BodyText"]

    story = [
        Paragraph("AI Contract Risk Assessment Report", title_style),
        Paragraph(f"Document: {document_filename}", body),
        Spacer(1, 0.2 * inch),
        Paragraph(f"Overall Risk Score: {analysis.get('risk_score', 0)} / 100", h2),
        Paragraph(f"Analysis Engine: {analysis.get('engine_used', 'rule_based')}", body),
        Paragraph("Executive Summary", h2),
        Paragraph(analysis.get("executive_summary") or "N/A", body),
        Paragraph("Key Contract Details", h2),
    ]

    details = [
        ["Contract Type", analysis.get("contract_type") or "N/A"],
        ["Parties", ", ".join(analysis.get("parties") or []) or "N/A"],
        ["Effective Date", analysis.get("effective_date") or "N/A"],
        ["Expiry Date", analysis.get("expiry_date") or "N/A"],
    ]
    table = Table(details, colWidths=[1.7 * inch, 4.3 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2f7")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(table)

    story.append(Paragraph("Clause Analysis", h2))
    for label, key in [
        ("Payment Terms", "payment_terms"),
        ("Renewal Clause", "renewal_clause"),
        ("Confidentiality Clause", "confidentiality_clause"),
        ("Termination Clause", "termination_clause"),
        ("Responsibilities", "responsibilities"),
    ]:
        story.append(Paragraph(f"<b>{label}:</b> {analysis.get(key) or 'N/A'}", body))
        story.append(Spacer(1, 0.05 * inch))

    story.append(Paragraph("Risk Findings", h2))
    risks = analysis.get("risks") or []
    if not risks:
        story.append(Paragraph("No risks detected.", body))
    for r in risks:
        story.append(Paragraph(
            f"<b>[{r.get('severity','').upper()}] {r.get('title')}</b> "
            f"(confidence: {round(r.get('confidence', 0) * 100)}%)", body
        ))
        story.append(Paragraph(r.get("explanation", ""), body))
        story.append(Spacer(1, 0.08 * inch))

    story.append(Paragraph("Recommended Actions", h2))
    for action in _bullet_list(analysis.get("recommended_actions")):
        story.append(Paragraph(f"• {action}", body))

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(
        "<i>Disclaimer: This report is generated by an AI system for informational purposes "
        "only and does not constitute legal advice. Consult a qualified attorney before making "
        "decisions based on this report.</i>", body
    ))

    doc.build(story)
    return output_path


def generate_docx_report(analysis: dict, document_filename: str, output_path: str) -> str:
    d = docx.Document()

    title = d.add_heading("AI Contract Risk Assessment Report", level=0)
    d.add_paragraph(f"Document: {document_filename}")
    d.add_paragraph(f"Overall Risk Score: {analysis.get('risk_score', 0)} / 100")
    d.add_paragraph(f"Analysis Engine: {analysis.get('engine_used', 'rule_based')}")

    d.add_heading("Executive Summary", level=1)
    d.add_paragraph(analysis.get("executive_summary") or "N/A")

    d.add_heading("Key Contract Details", level=1)
    table = d.add_table(rows=0, cols=2)
    table.style = "Light Grid Accent 1"
    for label, value in [
        ("Contract Type", analysis.get("contract_type") or "N/A"),
        ("Parties", ", ".join(analysis.get("parties") or []) or "N/A"),
        ("Effective Date", analysis.get("effective_date") or "N/A"),
        ("Expiry Date", analysis.get("expiry_date") or "N/A"),
    ]:
        row = table.add_row().cells
        row[0].text = label
        row[1].text = str(value)

    d.add_heading("Clause Analysis", level=1)
    for label, key in [
        ("Payment Terms", "payment_terms"),
        ("Renewal Clause", "renewal_clause"),
        ("Confidentiality Clause", "confidentiality_clause"),
        ("Termination Clause", "termination_clause"),
        ("Responsibilities", "responsibilities"),
    ]:
        p = d.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(analysis.get(key) or "N/A")

    d.add_heading("Risk Findings", level=1)
    risks = analysis.get("risks") or []
    if not risks:
        d.add_paragraph("No risks detected.")
    for r in risks:
        p = d.add_paragraph()
        run = p.add_run(f"[{r.get('severity','').upper()}] {r.get('title')} "
                         f"(confidence: {round(r.get('confidence', 0) * 100)}%)")
        run.bold = True
        if r.get("severity") == "high":
            run.font.color.rgb = RGBColor(0xC0, 0x00, 0x00)
        d.add_paragraph(r.get("explanation", ""))

    d.add_heading("Recommended Actions", level=1)
    for action in _bullet_list(analysis.get("recommended_actions")):
        d.add_paragraph(action, style="List Bullet")

    d.add_paragraph()
    disclaimer = d.add_paragraph()
    disclaimer.add_run(
        "Disclaimer: This report is generated by an AI system for informational purposes "
        "only and does not constitute legal advice."
    ).italic = True

    d.save(output_path)
    return output_path
